git:
  pagers:
    - externalDiffCommand: difft
    - pager: delta --dark --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"

gui:
  theme:
    selectedLineBgColor:
      - reverse
